pipeline:
  check_formatting:
    image: crystallang/crystal
    commands:
      - crystal tool format --check config/ db/ spec/ src/

  test:
    image: amberframework/amber:v0.7.2
    commands:
      # Sleep to ensure the DB is ready at this point
      - sleep 10
      - crystal spec

  docker_build:
    image: plugins/docker
    auto_tag: true
    repo: docker.netsoc.co/crnlpanic/nocturne
    registry: docker.netsoc.co
    secrets: [docker_username, docker_password]
    when:
      event: [push, tag]
      branch: master

services:
  test_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nocturne_test