# TODO: Add testing

pipeline:
  check_formatting:
    image: crystallang/crystal
    commands:
      - crystal tool format --check config/ db/ spec/ src/

  test:
    image: crystallang/crystal
    commands:
      - crystal spec

  docker_build:
    image: plugins/docker
    auto_tag: true
    repo: docker.netsoc.co/crnlpanic/nocturne
    registry: docker.netsoc.co
    secrets: [docker_username, docker_password]
    when:
      event: [push, tag]
      branch: master
