pipeline:
  check_formatting:
    image: crystallang/crystal
    commands:
      - crystal tool format --check config/ db/ spec/ src/
    when:
      event: push
      branch:
        excludes: master

  test:
    image: amberframework/amber:v0.7.2
    commands:
      # Sleep to ensure the DB is ready at this point
      - shards install
      # Wait for the DB to be up by polling
      - until psql -U postgres -d nocturne_test -h test_db -c "SELECT 1;" >/dev/null 2>&1; do sleep 1; done
      - amber db create migrate
      - crystal spec
    when:
      event: push
      branch:
        excludes: master

  docker_build:
    image: plugins/docker
    auto_tag: true
    repo: docker.netsoc.co/crnlpanic/nocturne
    registry: docker.netsoc.co
    secrets: [docker_username, docker_password]
    when:
      event: [push, tag]
      branch: master

services:
  test_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nocturne_test